kind: pipeline
name: merchant_api

clone:
  disable: true

steps:
  - name: docker-merchant
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/merchant_service
        #- git checkout -- .
        - git checkout stage
        #- git checkout -- .
        - git pull origin stage
        - git pull
        - go mod tidy
        - docker-compose -f down
        - docker rmi -f $(docker images --filter="reference=merchant_service" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o merchant merchant/merchant.go
        - docker build -t merchant_service -f .
        - docker-compose -f up -d
    when:
      branch:
        - stage
      event:
        - push
        
trigger:
  branch:
    - stage
