// Code generated by goctl. DO NOT EDIT.
package types

type PayOrderRequest struct {
	AccessType    string `json:"accessType, optional" validate:"required,max=2"`
	MerchantId    string `json:"merchantId, optional" validate:"required"`
	NotifyUrl     string `json:"notifyUrl, optional"  validate:"required,max=180"`
	PageUrl       string `json:"pageUrl, optional"`
	Language      string `json:"language, optional" validate:"required,max=8"`
	Sign          string `json:"sign, optional" validate:"required"`
	JumpType      string `json:"jumpType, optional" validate:"max=12"`
	LoginType     string `json:"loginType, optional" validate:"max=12"`
	OrderNo       string `json:"orderNo, optional" validate:"required,max=40"`
	OrderAmount   string `json:"orderAmount, optional" validate:"required"`
	Currency      string `json:"currency, optional" validate:"required"`
	PayType       string `json:"payType, optional" validate:"required"`
	OrderTime     string `json:"orderTime, optional" validate:"max=20"`
	OrderName     string `json:"orderName, optional" validate:"required,max=180"`
	BankCode      string `json:"bankCode, optional" validate:"max=12"`
	Phone         string `json:"phone, optional" validate:"max=18"`
	PayTypeNo     string `json:"payTypeNo, optional" validate:"max=4"`
	UserId        string `json:"userId, optional" validate:"max=255"`
	MerchantLevel string `json:"merchantLevel, optional" validate:"max=3"`
	UserIp        string `json:"userIp, optional" validate:"max=64"`
}

type InternalPayOrderRequest struct {
	ID       string `json:"id, optional" validate:"required"`
	UserName string `json:"userName, optional" validate:"required"`
}

type PayOrderChannelBankRequest struct {
	OrderNo string `json:"orderNo"`
}

type PayOrderChannelBankResponse struct {
	BankName   string  `json:"bankName"`
	CardNumber string  `json:"cardNumber"`
	CardName   string  `json:"cardName"`
	Amount     float64 `json:"amount"`
	Expiration float64 `json:"expiration"`
}

type PayOrderResponse struct {
	BankCode   string `json:"bankCode"`
	Info       string `json:"info"`
	PayOrderNo string `json:"payOrderNo"`
	RespCode   string `json:"respCode"`
	RespMsg    string `json:"respMsg"`
	Sign       string `json:"sign"`
	Status     int64  `json:"status"`
	Type       string `json:"type"`
}

type PayQueryRequest struct {
	AccessType string `json:"accessType, optional" validate:"required"`
	MerchantId string `json:"merchantId, optional" validate:"required"`
	Sign       string `json:"sign, optional" validate:"required"`
	Language   string `json:"language, optional"`
	OrderNo    string `json:"orderNo, optional" validate:"required"`
	PayTypeNo  string `json:"payTypeNo, optional"`
}

type PayQueryResponse struct {
	RespCode     string `json:"respCode"`
	RespMsg      string `json:"respMsg"`
	Language     string `json:"language"`
	BankCode     string `json:"bankCode"`
	Fee          string `json:"fee"`
	MerchantId   string `json:"merchantId"`
	OrderAmount  string `json:"orderAmount"`
	OrderNo      string `json:"orderNo"`
	OrderTime    string `json:"orderTime"`
	PayOrderId   string `json:"payOrderId"`
	PayOrderTime string `json:"payOrderTime"`
	OrderStatus  string `json:"orderStatus"`
	Sign         string `json:"sign"`
}

type PayQueryBalanceRequest struct {
	AccessType string `json:"accessType, optional" validate:"required"`
	MerchantId string `json:"merchantId, optional" validate:"required"`
	Sign       string `json:"sign, optional" validate:"required"`
	Currency   string `json:"currency, optional" validate:"max=5"`
}

type PayQueryBalanceResponse struct {
	RespCode        string `json:"respCode"`
	RespMsg         string `json:"respMsg"`
	PayAmount       string `json:"payAmount"`
	ProxyAmount     string `json:"proxyAmount"`
	AvailableAmount string `json:"availableAmount"`
	FrozenAmount    string `json:"frozenAmount"`
	Sign            string `json:"sign"`
}

type PayCallBackRequest struct {
	CallbackTime   string  `json:"callbackTime"`
	ChannelOrderNo string  `json:"channelOrderNo"`
	OrderAmount    float64 `json:"orderAmount"`
	OrderStatus    string  `json:"orderStatus"`
	PayOrderNo     string  `json:"payOrderNo"`
}

type PayCallBackResponse struct {
	RespCode string `json:"respCode"`
	RespMsg  string `json:"respMsg"`
	Status   int64  `json:"status"`
	Data     int64  `json:"data"`
}

type TestMerchantPayCallBackRequest struct {
	AccessType   string `json:"accessType"`
	Language     string `json:"language"`
	MerchantId   string `json:"merchantId"`
	OrderNo      string `json:"orderNo"`
	OrderAmount  string `json:"orderAmount"`
	OrderTime    string `json:"orderTime"`
	PayOrderTime string `json:"payOrderTime"`
	Fee          string `json:"fee"`
	OrderStatus  string `json:"orderStatus"`
	PayOrderId   string `json:"payOrderId"`
	Sign         string `json:"sign"`
}

type ProxyPayOrderRequest struct {
	AccessType   string  `json:"accessType" validate:"max=2"`
	MerchantId   string  `json:"merchantId" valiate: "required"`
	Sign         string  `json:"sign" valiate: "required"`
	NotifyUrl    string  `json:"notifyUrl" validate: "required"`
	Language     string  `json:"language" valiate: "required"`
	OrderNo      string  `json:"orderNo" validate: "required"`
	BankId       string  `json:"bankId" validate: "required"`
	BankName     string  `json:"bankName" validate: "required"`
	BankProvince string  `json:"bankProvince" validate: "required"`
	BankCity     string  `json:"bankCity" validate: "required"`
	BranchName   string  `json:"branchName, optional"`
	BankNo       string  `json:"bankNo" valiate: "required"`
	OrderAmount  float64 `json:"orderAmount" validate: "required"` //到小數兩位
	DefrayName   string  `json:"defrayName" validate: "required"`
	DefrayId     string  `json:"defrayId, optional"`
	DefrayMobile string  `json:"defrayMobile, optional"`
	DefrayEmail  string  `json:"defrayEmail, optional"`
	Currency     string  `json:"currency" validate: "required"`
	PayTypeSubNo string  `json:"payTypeSubNo,optional"`
}

type ProxyPayOrderResponse struct {
	RespCode    string `json:"respCode"`
	RespMsg     string `json:"respMsg"`
	MerchantId  string `json:"merchantId"`
	OrderNo     string `json:"orderNo"`
	PayOrderNo  string `json:"payOrderNo"`
	OrderStatus string `json:"orderStatus"`
	Sign        string `json:"sign"`
}

type ProxyPayOrderQueryRequest struct {
	AccessType string `json:"accessType" valiate: "required"`
	MerchantId string `json:"merchantId" valiate: "required"`
	OrderNo    string `json:"orderNo" valiate: "required"`
	Sign       string `json:"sign" valiate: "required"`
	Language   string `json:"language" valiate: "required"`
}

type ProxyPayOrderQueryResponse struct {
	RespCode       string `json:"respCode"`
	RespMsg        string `json:"respMsg"`
	MerchantId     string `json:"merchantId"`
	OrderNo        string `json:"orderNo"`
	LastUpdateTime string `json:"lastUpdateTime"`
	PayOrderNo     string `json:"payOrderNo"`
	OrderStatus    string `json:"orderStatus"`
	CallbackStatus string `json:"callbackStatus"`
	OrderAmount    string `json:"orderAmount"`
	Fee            string `json:"fee"`
	Sign           string `json:"sign"`
}

type ProxyPayOrderCallBackRequest struct {
	ProxyPayOrderNo     string  `json:"proxyPayOrderNo"`     // 平台订单号
	ChannelOrderNo      string  `json:"channelOrderNo"`      //渠道商回复单号
	ChannelResultAt     string  `json:"channelResultAt"`     //渠道商回复日期  //(YYYYMMDDhhmmss)
	ChannelResultStatus string  `json:"channelResultStatus"` //渠道商回复处理状态  //(Dior渠道商范例：状态 0处理中，1成功，2失败) */
	ChannelResultNote   string  `json:"channelResultNote"`   //渠道商回复处理备注
	Amount              float64 `json:"amount"`              //代付金额
	ChannelCharge       float64 `json:"channelCharge"`       //渠道商成本
	UpdatedBy           string  `json:"updatedBy"`           //更新人员
}

type ProxyPayOrderCallBackResponse struct {
	RespCode string `json:"respCode"`
	RespMsg  string `json:"respMsg"`
	Status   int    `json:"status"`
	Data     string `json:"data"`
}

type BoadminProxyRespVO struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
	TraceId string `json:"traceId"`
}

type MerchantCallBackReqeuest struct {
	MerchantId   string `json:"merchantId"`
	OrderNo      string `json:"orderNo"`
	PayOrderNo   string `json:"payOrderNo"`
	OrderStatus  string `json:"orderStatus"`
	OrderAmount  string `json:"orderAmount"`
	Fee          string `json:"fee"`
	PayOrderTime string `json:"payOrderTime"`
}

type RespData struct {
	WithdrawOrderNo string `json:"withdrawOrderNo"`
	Sign            string `json:"sign"`
}

type WithdrawApiOrderRequest struct {
	MerchantId   string `json:"merchantId"`
	Sign         string `json:"sign"`
	NotifyUrl    string `json:"notifyUrl"`
	PageUrl      string `json:"pageUrl, optional"`
	WithdrawName string `json:"withdrawName"`
	BankName     string `json:"bankName"`
	AccountNo    string `json:"accountNo"`
	BankProvince string `json:"bankProvince, optional"`
	BankCity     string `json:"bankCity, optional"`
	OrderAmount  string `json:"orderAmount"`
	Language     string `json:"language"`
	OrderNo      string `json:"orderNo"`
	Currency     string `json:"currency"`
}

type WithdrawApiOrderResponse struct {
	RespCode string   `json:"respCode"`
	RespMsg  string   `json:"respMsg"`
	RespData RespData `json:"data"`
	Trace    string   `json:"trace"`
}

type WithdrawApiQueryRequest struct {
	MerchantId string `json:"merchantId"`
	OrderNo    string `json:"orderNo"`
	Sign       string `json:"sign"`
}

type WithdrawApiQueryResponse struct {
	RespCode    string `json:"respCode"`
	RespMsg     string `json:"respMsg"`
	OrderStatus string `json:"orderStatus"`
	MerchantId  string `json:"merchantId"`
	OrderAmount string `json:"orderAmount"`
	Sign        string `json:"sign"`
}

type SystemRate struct {
	ID                  int64   `json:"id"`
	CurrencyCode        string  `json:"currencyCode"`
	WithdrawHandlingFee float64 `json:"withdrawHandlingFee"`
	MinWithdrawCharge   float64 `json:"minWithdrawCharge"`
	MaxWithdrawCharge   float64 `json:"maxWithdrawCharge"`
	CreatedBy           string  `json:"createdBy"`
	UpdatedBy           string  `json:"updatedBy"`
}

type GenerateSignRequest struct {
}

type TestPayOrderRequest struct {
	Currency    string `json:"currency" validate:"max=5"`
	PayType     string `json:"payType" validate:"max=8"`
	PayTypeNo   string `json:"payTypeNo, optional" validate:"max=4"`
	OrderAmount string `json:"orderAmount"`
	IP          string `json:"ip"`
	BankCode    string `json:"bankCode, optional"`
	JumpType    string `json:"jumpType, optional" validate:"max=12"`
	MerchantId  string `json:"merchantId"`
	MerchantKey string `json:"merchantKey"`
}
